# Generated by Django 4.1.3 on 2022-11-10 04:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Workout",
            new_name="Event",
        ),
        migrations.RemoveField(
            model_name="set",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="templateexercise",
            name="workout",
        ),
        migrations.RemoveField(
            model_name="templateset",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="wellness",
            name="user",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="Set",
        ),
        migrations.DeleteModel(
            name="TemplateExercise",
        ),
        migrations.DeleteModel(
            name="TemplateSet",
        ),
        migrations.DeleteModel(
            name="Wellness",
        ),
    ]
